sudo: false
language: node_js
node_js:
  - "5.5"
branches:
  only:
    - gh-pages
    - /.*/
before_install: npm install -g grunt-cli
cache:
  directories:
    - node_modules
notifications:
  email: false
